[world]
name = "Scard"
description = "Scar'd"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/scard"
seed = "scard-sepolia"

[namespace]
default = "scard"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x0379b60e4b9bf04c0429c4830c6e1fd9f2ea0acf74cbe8583043e6f9f0db8607"
account_address = "0x04a3c285d6bf785684a3f3ae89f48a0998411a8e1ff4d8b539170981c3145874"
keystore_path = "../deployments/my_key.json"

[writers]
"scard" = ["scard-game_systems", "scard-game_token_systems"]

[migration]
order_inits = ["scard-game_token_systems"]

[init_call_args]
"scard-game_token_systems" = [
    "0x02CA2BAE77044D5646F0fc7Aaa0eDb75BDfA17a5F62635E8fddf930B26D4E764", # creator account address
    "0x02334dc9c950c74c3228e2a343d495ae36f0b4edf06767a679569e9f9de08776", # denshokan address
    "1",                                                                  # Option::None for renderer address
]
