[package]
cairo-version = "2.12.2"
name = "scard"
version = "1.7.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = "1.7.1"
starknet = "2.12.2"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
game_components_minigame = { path = "../../game-components/packages/minigame" }
game_components_token = { path = "../../game-components/packages/token" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.1"
dojo_snf_test = "1.7.1"
snforge_std = "0.48.0"

[scripts]
migrate = "sozo build && sozo migrate"
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros", "snforge_std"]

[profile.sepolia]
