world_address = "0x0379b60e4b9bf04c0429c4830c6e1fd9f2ea0acf74cbe8583043e6f9f0db8607"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# [events]
# raw = true

[events]
historical = [
  "scard-GameCreated",
  "scard-Moved",
  "scard-EncounterGenerated",
  "scard-GameWon",
]

[indexing]
pending = true
contracts = [
  # "erc721:0x06a1102ed881e0d6d689295db5819dd1d15f0d55cbe10e1b87587c2ea1ec8da4", # denshokan
  "ERC721:0x02334dc9c950c74c3228e2a343d495ae36f0b4edf06767a679569e9f9de08776", # DENSHOKAN SEPOLIA
]
